# Generated by Django 4.1.3 on 2022-11-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculo',
            old_name='emal',
            new_name='email',
        ),
    ]
